##PBS -N yh-JOB
#PBS -l nodes=comput8:ppn=1
#PBS -q blade
#PBS -l walltime=960:00:00
#PBS -d /public3/home/wangzn/yuanhao/penguin/TEexpansion/ann/earlGrey/ADL.v6b/strained9/ERVK/rmblast
##PBS -d /public1/home/wangzn/yuanhao
##PBS -e yh-JOB.err
##PBS -o yh-JOB.out

source ~/.bashrc

#source ~/Software/Common/miniforge3/bin/activate
#conda activate ENV

#export PERL5LIB=/

genome='ADL.v6b.fa'
concensus='ADL.earlGrey.families.ERVK-full.fa'
species='ADL.v6b'

ln -s /public3/home/wangzn/yuanhao/penguin/genome/ADL.v6b/ADL.v6b.fa
ln -s ../ADL.earlGrey.families.ERVK-full.fa

makeblastdb -dbtype nucl -in ./${genome} -out ./${genome}

/public3/home/wangzn/Software/Annotation/RepeatModeler/RMBlast/rmblast-2.10.0/bin/rmblastn -query ./ADL.earlGrey.families.ERVK-full.fa -db ./${genome} -num_threads 16 -outfmt 6 -out ${species}.full-ERVK.rmblastn.out -logfile ${species}.full-ERVK.rmblastn.out.log -gapopen 5 -gapextend 2
